<a href="https://colab.research.google.com/github/aliyusifov99/python_course/blob/main/Extra_Numpy_And_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numpy is one of the most important libraries in python to deal with numbers. Numpy means numerical python. Numpy works much faster with numbers than normal python list and dictionaries. If you are interested in data science and machine learning you should learn numpy and it is beginning of Data Science.

In [2]:
import numpy as np

In [3]:
# creating array with 0s
a=np.zeros(3)
a

array([0., 0., 0.])

In [4]:
a.shape

(3,)

In [6]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [9]:
# creating an array with linspace
a=np.linspace(2,10,5) #from 2 to 10 with 5 elements
a

array([ 2.,  4.,  6.,  8., 10.])

In [10]:
a=np.array([10,20,30])
a

array([10, 20, 30])

In [12]:
# creatingg list and convert it to array
a_list=[1,2,3,4,5,56,78]
a=np.array(a_list)
a

array([ 1,  2,  3,  4,  5, 56, 78])

In [16]:
#sum 
np.sum(a)

149

In [17]:
#min
np.min(a)

1

In [18]:
#max
np.max(a)

78

In [19]:
#mean 
np.mean(a)

21.285714285714285

In [20]:
a<10

array([ True,  True,  True,  True,  True, False, False])

# Pandas

Pandas is one of the popular libraries to analyse csv files or we can call it tabular data.

In [22]:
#Creating a dataframe
weather_list=[
              {
                  'Country': 'Azerbaijan',
                  'Weather': 'Sunny'
              },
              {
                  'Country':'Malaysia',
                  'Weather':'Rainy'
              },
              {
                  'Country':'France',
                  'Weather':'Cloudy'
              }
]

import pandas as pd

weather_dataframe=pd.DataFrame(weather_list)
weather_dataframe

Country Weather
0  Azerbaijan   Sunny
1    Malaysia   Rainy
2      France  Cloudy

In [23]:
# import dataset from outside
titanic_dataframe=pd.read_csv('/content/Iris.csv')

In [24]:
titanic_dataframe

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [25]:
titanic_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [26]:
titanic_dataframe.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000